apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-idca-deployment
spec:
  service:
    type: NodePort
  persistence:
    storage: "2Gi"
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 2Gi
  rabbitmq:
    additionalConfig: |
      auth_backends.1 = rabbit_auth_backend_oauth2
      auth_backends.2 = internal
      log.file.level = info
    advancedConfig: |
      [
        {rabbitmq_auth_backend_oauth2, [
          {resource_server_id, <<"arthur">>},
          {key_config, [
            {jwks_url, <<"http://172.17.0.1:8081/auth/realms/dc/protocol/openid-connect/certs">>}
          ]}
        ]}
      ].
    additionalPlugins:
      - rabbitmq_auth_backend_oauth2
    

