apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: icerabbitmq
  namespace: rabbitmq-system
spec:
  replicas: 1
  service:
    type: NodePort
  persistence:
    storage: 2Gi
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 2Gi
  rabbitmq:
    additionalConfig: |
      auth_backends.1 = rabbit_auth_backend_oauth2
      auth_backends.2 = internal
      log.file.level = debug
    advancedConfig: |
      [
        {rabbitmq_auth_backend_oauth2, [
          {resource_server_id, <<"%RES_SRV%">>},
          {key_config, [
            {jwks_url, <<"http://%EXT_IP%:%KEYCLOAK_PORT%/auth/realms/%REALM%/protocol/openid-connect/certs">>}
          ]}
        ]}
      ].
    additionalPlugins:
      - rabbitmq_auth_backend_oauth2
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: icerabbitmq
  namespace: rabbitmq-system
spec:
  rules:
  - host: rabbitmq-management.%EXT_IP%.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: icerabbitmq
            port: 
              number: 15672